### ISSUE TITLE
Learn to fly & learn to fly 2 is broken

### ISSUE THREAD

**Issue by MRPENGUINTHEFIRST1** [SHSGames/shsgames.github.io#180] opened 2021-11-18 16:44 UTC
In learn to Fly 1&2 the puppet will only go up slowly and you can't launch. And, Learn to fly 1 is just Learn to fly 2 and has the same issue . Please Fix!!!

**Comment by JoshMerlino** [comment] 2021-12-04 18:11
This appears to be a problem with ruffle-rs/ruffle. Unfortunately all I can do is display a warning.

**Comment by JoshMerlino** [comment] 2021-12-04 18:12
And for reference: The problems I'm running into are physics aren't implemented correctly.

**Comment by Woahcheeto** [comment] 2021-12-10 13:33
@JoshMerlino is that possible to fix?

**Comment by JoshMerlino** [comment] 2022-03-18 01:05
Duplicate of #350. Please seek support within that issue.

**Closed by JoshMerlino** 2022-03-18 01:05 UTC
Labels: duplicate, game, ruffle
