### ISSUE TITLE
Fix Learn to fly

### ISSUE THREAD

**Issue by Defualted** [SHSGames/shsgames.github.io#156] opened 2021-11-11 21:39 UTC
I cannot play learn to fly #1 or #2 on mobile please fix… Thank you!

**Comment by Defualted** [comment] 2021-11-12 15:23
Also fix it on computer the first game you just hover up very slowly please fix. and hurry! Thank you.

**Comment by MRPENGUINTHEFIRST1** [comment] 2021-11-18 16:45
popcorn

**Comment by JoshMerlino** [comment] 2021-12-03 01:08
Compatibility on mobile is not officially supported by Ruffle to my knowledge.
This is a duplicate of #180

**Closed by JoshMerlino** 2021-12-03 01:08 UTC
Labels: duplicate
